version: 0.2

phases: 
  install:
    commands:
      # install Node 12 (and npm)
      - curl -fsSL https://deb.nodesource.com/setup_15.x | -E bash -
      - apt install -y nodejs
  pre_build:
      commands:
      # install dependencies
      - npm install
  build:
      commands:
      # tests
      # build
      - npm run-script build
artifacts:
  files:
    - "**/*"
  discard-paths: no
  base-directory: build