version: 0.2

phases: 
  # install:
    # commands:
      # Node is preinstalled
  pre_build:
      commands:
      # install dependencies
      - npm install
  build:
      commands:
      # tests
      # build
      - npm run-script build
artifacts:
  files:
    - "**/*"
  discard-paths: no
  base-directory: build